const songs=[['01','告白氣球','周杰倫'],['02','小幸運','田馥甄'],['03','知足','五月天'],['04','修煉愛情','林俊傑'],['05','你，好不好','周興哲'],['06','那些年','胡夏'],['07','甲乙丙丁','李佳薇'],['08','愛你','王心凌'],['09','眉飛色舞','鄭秀文'],['10','我相信','楊培安'],['11','心花開','李千娜']].map(([id,title,artist])=>({id,title,artist,available:true,localFile:''}));
const $=id=>document.getElementById(id),audio=$('audio');let current=0;
function formatTime(seconds){if(!Number.isFinite(seconds)||seconds<0)return'0:00';return`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`}
function mediaUrl(song){return song.localFile||`/ktv/media/${song.id}.mp4?v=h264-20261003`}
function showMessage(text=''){$('message').textContent=text}
function updatePlaybackState(){const playing=!audio.paused&&!audio.ended;$('player').classList.toggle('is-playing',playing);$('statusText').textContent=playing?'正在播放':audio.currentTime>0?'已暫停':'準備播放';$('playBtn').textContent=playing?'❚❚':'▶';$('playBtn').setAttribute('aria-label',playing?'暫停':'播放');document.querySelectorAll('.song-row').forEach((row,index)=>{if(index===current)row.querySelector('.row-state').textContent=playing?'❚❚':'▶'})}
function updateTimeline(){const duration=Number.isFinite(audio.duration)?audio.duration:0,progress=duration?audio.currentTime/duration*100:0;$('timeline').value=progress;$('timeline').style.setProperty('--progress',`${progress}%`);$('currentTime').textContent=formatTime(audio.currentTime);$('duration').textContent=formatTime(duration)}
function render(){const song=songs[current];$('songNumber').textContent=`TRACK ${song.id} / ${String(songs.length).padStart(2,'0')}`;$('title').textContent=song.title;$('artist').textContent=song.artist;$('prevBtn').disabled=current===0;$('nextBtn').disabled=current===songs.length-1;$('songRows').innerHTML=songs.map((item,index)=>`<button class="song-row ${index===current?'active':''}" data-index="${index}" type="button" aria-label="播放 ${item.title}，${item.artist}"><span class="row-number">${item.id}</span><span class="song-meta"><strong>${item.title}</strong><small>${item.artist}</small></span><span class="row-state">${index===current?'▶':'♪'}</span></button>`).join('');document.querySelectorAll('.song-row').forEach(row=>row.onclick=()=>selectSong(Number(row.dataset.index),true));updatePlaybackState()}
function loadCurrent(){const src=mediaUrl(songs[current]);if(audio.getAttribute('src')!==src){audio.src=src;audio.load()}}
async function play(){const song=songs[current];if(!song.available){showMessage(`「${song.title}」的音樂檔目前無法使用。`);return}loadCurrent();showMessage();try{await audio.play()}catch(error){showMessage(`無法播放「${song.title}」，請確認音樂檔是否存在。`)}}
async function selectSong(index,autoplay=true){if(index<0||index>=songs.length)return;audio.pause();current=index;audio.removeAttribute('src');audio.load();updateTimeline();render();if(autoplay)await play()}
function seekBy(seconds){if(!Number.isFinite(audio.duration))return;audio.currentTime=Math.min(audio.duration,Math.max(0,audio.currentTime+seconds));updateTimeline()}
async function refreshAvailability(){await Promise.all(songs.map(async song=>{try{const response=await fetch(`/api/ktv/songs/${song.id}/status`);if(!response.ok)return;const result=await response.json();song.available=result.status==='downloaded';song.localFile=result.localFile||''}catch(_){}}))}
$('playBtn').onclick=()=>audio.paused?play():audio.pause();$('backBtn').onclick=()=>seekBy(-5);$('forwardBtn').onclick=()=>seekBy(5);$('prevBtn').onclick=()=>selectSong(current-1,true);$('nextBtn').onclick=()=>selectSong(current+1,true);$('timeline').oninput=event=>{if(Number.isFinite(audio.duration))audio.currentTime=audio.duration*(Number(event.target.value)/100);updateTimeline()};
audio.addEventListener('play',updatePlaybackState);audio.addEventListener('pause',updatePlaybackState);audio.addEventListener('ended',()=>{updatePlaybackState();if(current<songs.length-1)selectSong(current+1,true)});audio.addEventListener('timeupdate',updateTimeline);audio.addEventListener('loadedmetadata',updateTimeline);audio.addEventListener('durationchange',updateTimeline);audio.addEventListener('error',()=>{if(audio.getAttribute('src'))showMessage(`「${songs[current].title}」載入失敗，請確認音樂檔是否存在。`);updatePlaybackState()});
window.addEventListener('keydown',event=>{if(['INPUT','TEXTAREA','SELECT'].includes(event.target.tagName))return;if(event.code==='Space'){event.preventDefault();audio.paused?play():audio.pause()}else if(event.key==='ArrowLeft'){event.preventDefault();seekBy(-5)}else if(event.key==='ArrowRight'){event.preventDefault();seekBy(5)}});
render();refreshAvailability();
