const defaults=[
['01','告白氣球','周杰倫','bu7nU9Mhpyo',3],['02','小幸運','田馥甄','_sQSXwdtxlY',0],['03','知足','五月天','_o0oeyCtoFA',0],['04','修煉愛情','林俊傑','LWV-f6dMN3Q',0],['05','你，好不好','周興哲','wSBXfzgqHtE',0],['06','那些年','胡夏','KqjgLbKZ1h0',0],['07','甲乙丙丁','李佳薇','YacpC7sUXMM',0],['08','愛你','王心凌','NAODcPQcy9U',0],['09','眉飛色舞','鄭秀文','nf0Ljc1lVQs',0],['10','我相信','楊培安','V5b-kzEbwA8',0],['11','心花開','李千娜','Qd33i-OoOk4',0]
].map(([id,title,artist,videoId,startTime])=>({id,title,artist,videoId,youtubeUrl:`https://www.youtube.com/watch?v=${videoId}`,startTime,duration:10,status:'not-downloaded',localFile:''}));
let songs=JSON.parse(localStorage.getItem('ktv-html-games-songs')||'null')||defaults.map(x=>({...x}));let current=3;let loadingSong='';
const $=id=>document.getElementById(id),audio=$('audio');
function save(){localStorage.setItem('ktv-html-games-songs',JSON.stringify(songs))}function msg(text,kind='ok'){ $('message').innerHTML=text?`<div class="message ${kind}">${text}</div>`:'' }
function statusText(s){return {downloaded:'已下載',downloading:'下載中',failed:'下載失敗','not-downloaded':'尚未下載'}[s]||s}
async function refresh(){await Promise.all(songs.map(async s=>{try{const r=await fetch(`/api/ktv/songs/${s.id}/status`).then(x=>x.json());s.status=r.status;s.localFile=r.localFile||''}catch(e){}}));render()}
function render(){const s=songs[current];$('num').textContent=`第 ${current+1} / ${songs.length} 題`;$('title').textContent=s.title;$('artist').textContent=s.artist;$('prevBtn').disabled=!current;$('nextBtn').disabled=current===songs.length-1;$('songRows').innerHTML=songs.map((x,i)=>`<button class="row ${i===current?'now':''}" data-i="${i}"><strong>${x.id}</strong><span><strong>${x.title}</strong><small>${x.artist}</small></span><span class="state">${i===current?'◀ NOW':i<current?'✓ 已使用':statusText(x.status)}</span></button>`).join('');document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>select(+b.dataset.i));$('editRows').innerHTML=songs.map((x,i)=>`<div class="edit"><b>${x.id}</b><input data-f="title" data-i="${i}" value="${x.title}"><input data-f="artist" data-i="${i}" value="${x.artist}"><input data-f="youtubeUrl" data-i="${i}" value="${x.youtubeUrl}"><label>開始<input type="number" min="0" data-f="startTime" data-i="${i}" value="${x.startTime}"></label><label>秒數<input type="number" min="1" data-f="duration" data-i="${i}" value="${x.duration}"></label><button data-d="${i}">${statusText(x.status)}</button></div>`).join('');document.querySelectorAll('[data-f]').forEach(el=>el.onchange=()=>{songs[+el.dataset.i][el.dataset.f]=el.dataset.f==='startTime'||el.dataset.f==='duration'?+el.value:el.value;save()});document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>download(songs[+b.dataset.d]))}
async function download(s){s.status='downloading';render();msg(`${s.title} 下載中…`);try{const r=await fetch(`/api/ktv/songs/${s.id}/download`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({youtubeUrl:s.youtubeUrl})}).then(x=>x.json());s.status=r.status;s.localFile=r.localFile||'';msg(r.status==='downloaded'?`${s.title} 已下載完成`:(r.error||`${s.title} 下載失敗`),r.status==='downloaded'?'ok':'error')}catch(e){s.status='failed';msg(`${s.title} 下載失敗：${e.message}`,'error')}save();render()}
async function all(){ $('allBtn').disabled=true;for(const s of songs)if(s.status!=='downloaded')await download(s);$('allBtn').disabled=false;msg('全部下載流程完成');}
function stop(){audio.pause();audio.currentTime=0}async function load(s){stop();if(s.status!=='downloaded'){msg('此歌曲尚未下載','error');return false}if(loadingSong===s.id)return false;loadingSong=s.id;audio.src=s.localFile||`/ktv/media/${s.id}.mp4?v=h264-20261003`;audio.load();loadingSong='';return true}
async function play(replay=false){const s=songs[current];if(!audio.src||!audio.src.includes(`/${s.id}.mp4`)){if(!await load(s))return}if(replay||audio.currentTime<s.startTime||audio.currentTime>=s.startTime+s.duration)audio.currentTime=s.startTime;try{await audio.play()}catch(e){msg(`播放失敗：${e.message}`,'error')}}
async function select(i){stop();current=i;await load(songs[current]);render()}audio.ontimeupdate=()=>{const s=songs[current];if(audio.currentTime>=s.startTime+s.duration)stop()};$('playBtn').onclick=()=>play();$('pauseBtn').onclick=()=>audio.pause();$('stopBtn').onclick=stop;$('replayBtn').onclick=()=>play(true);$('prevBtn').onclick=()=>select(Math.max(0,current-1));$('nextBtn').onclick=()=>select(Math.min(songs.length-1,current+1));$('allBtn').onclick=all;$('settingsBtn').onclick=()=>{$('settings').hidden=false};$('hostBtn').onclick=()=>{$('settings').hidden=true};window.onkeydown=e=>{if(['INPUT','TEXTAREA'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();audio.paused?play():audio.pause()}else if(e.key==='ArrowLeft')$('prevBtn').click();else if(e.key==='ArrowRight')$('nextBtn').click();else if(e.key==='Escape')stop();else if(e.key.toLowerCase()==='r')play(true)};render();refresh();
