const test = require('node:test');
const assert = require('node:assert/strict');
const { World } = require('../youtube-world.js');
function quiet(n=1) { const w=new World(14,n); Object.assign(w.options,{autoFaults:false,autoRepair:false,arrivals:false});return w; }
function until(w,p,limit=200){for(let i=0;i<limit*10;i++){if(p())return;w.step(.1);}assert.ok(p(),'condition not reached');}
test('100 persistent sessions include the selected role and share request ledger',()=>{const w=quiet(100);w.step(90);assert.equal(w.users.length,100);assert.ok(w.seq.request>100);assert.ok(w.requests.some(r=>r.userId===1&&r.kind==='segment'));assert.ok(w.user(1).position>0);});
test('offline drains existing buffer, waits, then resumes same session',()=>{const w=quiet();w.step(10);const u=w.user(1),before=u.position,buffer=u.buffer;u.network='offline';w.step(20);assert.equal(u.buffer,0);assert.equal(u.status,'離線等待');assert.ok(Math.abs(u.position-before-buffer)<.2);u.network='good';w.step(30);assert.ok(u.position>before+buffer);assert.equal(u.id,1);});
test('CDN cannot bypass last-mile weak zone; adaptation and recovery share player',()=>{const w=quiet();w.step(30);w.moveUser(1,'tw',.8,.8);w.step(40);assert.equal(w.network(w.user(1)).mbps,.3);assert.ok(w.metrics.bufferSeconds>0);assert.equal(w.user(1).nextQuality,'360p');w.moveUser(1,'tw',.2,.2);w.step(40);assert.ok(w.user(1).buffer>0);});
test('machine failure interrupts in-flight requests and retries surviving peer',()=>{const w=quiet();w.options.cdn=false;const m=w.machines.find(m=>m.kind==='stream'&&m.region==='tw');w.addMachine('stream','tw');until(w,()=>w.requests.some(r=>r.status==='running'&&r.machines.includes(m.id)));w.setMachine(m.id,false);w.step(20);assert.ok(w.metrics.failed>0);assert.ok(w.incidents.find(e=>e.machineId===m.id).affected.has(1));assert.ok(w.user(1).position>5);assert.equal(m.up,false);});
test('resumable upload retains acknowledged parts and publishes same video',()=>{const w=quiet();const v=w.upload(1,12);until(w,()=>v.chunks.filter(c=>c.status==='acked').length>=2);const count=v.chunks.filter(c=>c.status==='acked').length;const storage=w.machines.find(m=>m.kind==='storage');w.setMachine(storage.id,false);w.step(5);assert.equal(v.chunks.filter(c=>c.status==='acked').length,count);w.setMachine(storage.id,true);until(w,()=>v.status==='ready');assert.equal(v.chunks.filter(c=>c.status==='acked').length,6);assert.deepEqual(v.renditions.slice().sort(),['360p','480p','720p']);assert.equal(w.user(1).videoId,v.id);assert.ok(w.requests.filter(r=>r.kind==='chunk').every(r=>r.videoId===v.id));});
test('non-resumable mode loses prior acknowledgements on interruption',()=>{const w=quiet();w.options.resumable=false;const v=w.upload(1,12);until(w,()=>v.chunks.filter(c=>c.status==='acked').length>=2);const m=w.machines.find(m=>m.kind==='storage');w.setMachine(m.id,false);w.step(5);assert.equal(v.chunks.filter(c=>c.status==='acked').length,0);});
test('worker retry preserves dependency graph and other completed renditions',()=>{const w=quiet();const v=w.upload(1,6);until(w,()=>v.renditions.includes('360p'));until(w,()=>w.requests.some(r=>r.videoId===v.id&&r.jobId==='720p'&&r.status==='running'));const job=w.requests.find(r=>r.videoId===v.id&&r.kind==='transcode'&&r.jobId==='720p'&&r.status==='running');assert.ok(job);const done=v.jobs.find(j=>j.id==='360p');w.setMachine(job.machines[0],false);w.step(5);assert.equal(done.status,'completed');until(w,()=>v.status==='ready');assert.equal(new Set(v.renditions).size,3);});
test('new service region changes no population location or historical service count',()=>{const w=quiet(100);w.step(5);const locations=w.users.map(u=>u.region);const r=w.addRegion('新加坡');assert.deepEqual(w.users.map(u=>u.region),locations);assert.equal(r.served.size,0);w.addUsers(100,r.id);assert.equal(w.users.length,200);assert.equal(w.users.filter(u=>u.region===r.id).length,100);});
test('wander runs during playback and movement changes weak-zone state',()=>{const w=quiet();w.options.wander=true;const before=[w.user(1).x,w.user(1).y];w.step(30);assert.notDeepEqual([w.user(1).x,w.user(1).y],before);assert.ok(w.user(1).position>0);});
test('continuous arrivals replace departed sessions without stopping at 100 requests',()=>{const w=quiet(20);w.options.arrivals=true;w.step(500);assert.equal(w.users.length,20);assert.ok(w.metrics.departed>0);assert.ok(w.seq.user>20);assert.ok(w.user(1));});
test('seeded clock produces identical outcomes regardless of frame batching',()=>{const a=quiet(12),b=quiet(12);a.options.autoFaults=b.options.autoFaults=true;a.step(90);for(let i=0;i<900;i++)b.step(.1);assert.deepEqual(a.summary(),b.summary());assert.deepEqual(a.users,b.users);assert.deepEqual(a.incidents,b.incidents);});
test('latest ledger remains newest first and never drops in-flight requests',()=>{const w=quiet(100);w.step(120);assert.ok(w.seq.request>500);assert.equal(w.requests[0].id,`REQ-${String(w.seq.request).padStart(5,'0')}`);w.users.filter(u=>u.pending).forEach(u=>assert.ok(w.requests.some(r=>r.id===u.pending)));assert.ok(w.requests.filter(r=>['completed','failed','cancelled'].includes(r.status)).length<=500);});
test('CDN outage falls back to origin after health detection',()=>{const w=quiet();w.step(20);const cdn=w.machines.find(m=>m.kind==='cdn'&&m.region==='tw');w.setMachine(cdn.id,false);w.step(25);assert.ok(w.requests.some(r=>r.kind==='segment'&&!r.cacheHit&&r.createdAt>22&&r.status==='completed'));assert.ok(w.user(1).position>20);});
